### ISSUE TITLE
Upgrade to node 20

### ISSUE THREAD

**Issue by chenghuang-mdsol** [srz-zumix/post-run-action#46]
i'm seeing this:

The following actions use a deprecated Node.js version and will be forced to run on node20: srz-zumix/post-run-action@v1. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Comment by srz-zumix** [comment]
https://github.com/srz-zumix/post-run-action/releases/tag/v2.0.0
I have released version 2. Thank you for your feedback.
